In [1]:
import numpy as np


In [3]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(a,b)

[1 2 3 4] [10 20 30 40]


In [9]:
#Element operations

#addition
print("Add the arrays together", a+b)

#subtracting
print("subtracting the array", 1-b)

#multiply
print("multiply", a*b)

#universal functions
print("square root", np.sqrt(a))
print("square root", np.sqrt(b))
print("expo", np.exp(b))

Add the arrays together [11 22 33 44]
subtracting the array [ -9 -19 -29 -39]
multiply [ 10  40  90 160]
square root [1.         1.41421356 1.73205081 2.        ]
square root [3.16227766 4.47213595 5.47722558 6.32455532]
expo [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]


In [17]:
#Create two arrays [5, 10, 15] and [2, 4, 6]. Perform addition, subtraction, multiplication, and division.
arrayone = np.array([5,10,15])
arraytwo = np.array([2,4,6])
print(arrayone , arraytwo)

addition = arrayone + arraytwo
subtraction = arrayone - arraytwo
multiply = arrayone * arraytwo
division =arrayone / arraytwo


print(addition)

print(subtraction)

print(multiply)

print(division)


[ 5 10 15] [2 4 6]
[ 7 14 21]
[3 6 9]
[10 40 90]
[2.5 2.5 2.5]


In [15]:
#Compute the cube (**3) of the first array
cube = arrayone**3
print(cube)

[ 125 1000 3375]


In [20]:
# Broadcasting
arr2 =np.array([1,2,3,4,5])

#add
print(arr2 +10)


[11 12 13 14 15]


In [22]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [25]:
# add a new array 10,20,30 to the mat
print("add array to exiting matrix", mat+ np.array([10,20,30]))

add array to exiting matrix [[11 22 33]
 [14 25 36]]


In [42]:
#Multiply an array [2, 4, 6, 8] by 0.5.
arr = np.array([2,4,6,8])
print(arr* 0.5)

#Create a 3×3 matrix and add np.array([1, 2, 3]) to it.

arr2 =np.array([1, 2, 3])
matrix3 = np.array([[1,2,4],[2,4,6],[7,8,9]])
print("add np.array([1,2,3]) ", matrix3 + arr2)


#Create a 2×3 matrix and add 10 to all elements.

matrix_2x3 = np.array([[1, 2, 3],
                       [4, 5, 6]])

added_10 = matrix_2x3 + 10

print("2×3 matrix after adding 10:\n", added_10)


[1. 2. 3. 4.]
add np.array([1,2,3])  [[ 2  4  7]
 [ 3  6  9]
 [ 8 10 12]]
2×3 matrix after adding 10:
 [[11 12 13]
 [14 15 16]]


In [44]:
import time

size = 10_000_000
#compare Python list with numpy

#Python list
list1 = list(range(size))
start = time.time()
list2 = [ x * 2 for x in list1]
print("Python list time:", time.time() - start)

#numpy array 
arr = np.arange(size)
start = time.time()
arr2 = arr * 2
print("numpy array time", time.time() - start)

Python list time: 0.3451998233795166
numpy array time 0.009607315063476562
