In [3]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [4]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [5]:
pip install numpy


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 1.6 MB/s  0:00:03 eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [8]:
#Create an array in Python
numbers =[1,2,3,4]
print(numbers)
# turned that python array into a numpy array
array = np.array(numbers)

[1, 2, 3, 4]


In [9]:
print(array)

[1 2 3 4]


In [11]:
doubled = array *2
print(doubled)


[2 4 6 8]


In [12]:
#zeros
zeros =np.zeros((2,3))
print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
#ones
ones = np.ones((3,))
print(ones)


[1. 1. 1.]


In [17]:
#RANGE_ARRAY
range_array = np.arange(0,10,2)
print(range_array)


[0 2 4 6 8]


In [22]:
#Create an array of numbers from 0–9
array0to9 = np.arange(0,10)
print(array0to9)
#Create a 4×4 matrix of ones.
fours = np.ones((4,4))
print(fours)
#Create 5 evenly spaced numbers between 0 and 1 using np.linspace.
array3 = np.linspace(0,1,5)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.   0.25 0.5  0.75 1.  ]


In [23]:
#Indexing and slicing


In [30]:
array5 = np.array([10,20,30,40,50])

#indexing
#get the first element from array5
print("first element", array5[0])
    
#get the last element from array5
print("last element", array5[-1])
#print
print("first three", array5[0:3])
#print every other element
print("every other element", array5[::2])

first element 10
last element 50
first three [10 20 30]
every other element [10 30 50]


In [33]:
arryeye = np.eye(4)
print(arryeye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
array7 = np.full((3,3),7)
print(array7)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [40]:
#2d arrays and indexing/ slicing with zero indexing
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("full matrix array", matrix)

full matrix array [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
#print the element at row 1 column 2
print("element in row1 , column2   ", matrix[0,1])

element in row1 , column2    2


In [58]:
#pick the second number from every row
print("every 2nd number from every row:", matrix[:,1])

every 2nd number from every row: [2 5 8]


In [51]:
#pick every row and choose the third number 
print("every row choose the third number", matrix[:,2])

 [3 6 9]


In [82]:
#Create an array of numbers 1–10. Slice out the first 5.
array10 = np.arange(1,11)
print("the first 5 elements: ", array10[:5])

#From the matrix above, extract the first two rows.
print("matrix first 2 row:", matrix[:2,:])

#From the matrix above, extract the bottom-right 2×2 sub-matrix.
print("the bottom-right 2×2 sub-matrix", matrix[1:,1:])

the first 5 elements:  [1 2 3 4 5]
matrix first 2 row: [[1 2 3]
 [4 5 6]]
the bottom-right 2×2 sub-matrix [[5 6]
 [8 9]]


In [83]:
#reshaping arrays
new_array = np.arange(1,13)
print(new_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [92]:
reshaped = new_array.reshape(3,4)
print(reshared)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [93]:
# Extact the submatrix of the top left 2x2
print("sub matrx 2x2 top left",reshaped[:2,:2])


sub matrx 2x2 top left [[1 2]
 [5 6]]


In [94]:
#flatten the array back to it original
flat = reshaped.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [112]:
#Reshape the array of numbers 1–12 into a 4X 3 matrix
reshaped2 = new_array.reshape(3,4)
print("reshaped",reshaped2)

#Extract the middle two columns.
print("Extract the middle two columns", reshaped2[:,1:3])

#Flatten the result into 1D.
flat2 = reshaped2.flatten()
print(flat2)

reshaped [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Extract the middle two columns [[ 2  3]
 [ 6  7]
 [10 11]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#How to create arrays from lists and with NumPy functions 
#How to use indexing a